blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.blog_details, name='blog_details'),
    path('<int:blog_id>/add/', views.add_comment, name='add_comment'),
    path('update/<int:comment_id>/',
         views.update_comment, name='update_comment'),
    path('delete/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('lectures/', views.all_lectures, name='lectures'),
    path('programs/', views.all_programs, name='programs'),
    path('lectures/<int:lecture_id>',
         views.lecture_details, name='lecture_details'),
    path('programs/<int:program_id>',
         views.program_details, name='program_details'),
]

virtual_yoga_room/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('items/', include('items.urls')),
    path('questions/', include('questions.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('profiles/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages


def view_cart(request):
    """ A view that renders the cart contents page """

    return render(request, 'cart/cart.html')


def add_to_cart(request, item_id):
    """ Add a quantity of the selected product/service to the cart """

    quantity = int(request.POST.get('quantity'))
    redirect_url = request.POST.get('redirect_url')
    cart = request.session.get('cart', {})

    if item_id in list(cart.keys()):
        messages.error(request, 'Items already in your cart!\
                Check your cart to continue booking.')
    else:
        cart[item_id] = quantity
        messages.success(request, 'Item was added to your cart')

    request.session['cart'] = cart
    print(request.session['cart'])
    return redirect(redirect_url)


def remove_from_cart(request, item_id):
    """Remove the item from the shopping cart"""

    try:
        cart = request.session.get('cart', {})
        print(cart)
        cart.pop(item_id)
        messages.info(request, ('Removed item from your cart'))

        request.session['cart'] = cart
        return HttpResponse(status=200)

    except Exception as e:
        return HttpResponse(status=500)

cart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}
{% block extra_title %}Shopping Cart{% endblock %}

{% block content %}
<header>
    {% include 'includes/main-nav.html' %}
</header>

<section class="margin-top-navbar">
    <!--Main content-->
    <div class="container-fluid" id="shopping-cart">

        <!--breadcrumbs row with active page-->
        <div class="row">
            <div class="col">
                {% include 'cart/includes/breadcrumbs.html' %}
            </div>
        </div>

        <!--title row-->
        <div class="row">
            <div class="col text-center my-3">
                <h2 class="heading-font heading-item pb-2">Shopping Cart</h2>
            </div>
        </div>
        <!--Shopping cart content-->
        <div class="row">
            <div class="col-12">
                {% if cart_items %}
                <div class="container border border-secondary mt-3 mb-5 shadow ">

                    <div class="row p-3">
                        {% for item in cart_items %}
                        <div class="col-12 col-md-6 col-lg-5 offset-lg-1">
                            <img src="{{ item.program.image.url }}" class="img-fluid">
                        </div>
                        <div class="col-12 col-md-6 col-lg-5 offset-lg-1">
                            <h4 class="font-weight-bold"> {{ item.program.name }}</h4>
                            <p class="text-muted">Includes {{ item.program.number_lectures }} lectures</p>
                            <p class="text-dark">£{{ item.program.price }}</p>

                            {% if item.program.sku %}
                            <p class="my-0 small text-muted uppercase">SKU:&nbsp;{{ item.program.sku }}</p>
                            {% endif %}

                            <!--Remove button -->
                            {% include 'cart/includes/remove-item.html' %}
                        </div>

                        <hr class="mt-3">


                        {% endfor %}
                    </div>
                    <!--Cart Grand Total-->
                    <div class="row">
                        <div class="col-12 col-md-11 d-flex align-items-end flex-column my-3">
                            <h6 class="font-weight-bold">Cart&nbsp;Total: €&nbsp;{{ total|floatformat:2 }}</h6>
                            <small class="text-muted">*Tax&nbsp;included </small>

                            <a href="" class="btn button-logo-green uppercase shadow my-4 btn-lg">
                                <i class="fas fa-lock mr-3"></i>&nbsp;Checkout
                            </a>
                        </div>
                    </div>

                    {% else %}
                    <p class="lead mb-5">Your cart is empty.</p>
                    <a href="{% url 'items:programs' %}"
                        class="btn btn-lg text-decoration-none bg-logo-green mb-5 d-flex justify-content-center align-items-center"><i
                            class="fas fa-angle-double-left fa-lg me-2"></i> Continue Shopping</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block extra_js %}
{{ block.super }}


<script src="{% static 'js/quantity_input.js' %}"></script> 
<!-- <script src="{% static 'js/number_of_participants_input.js' %}"></script>  -->

<script type="text/javascript">
    // Remove item from the cart and reload the page on click
     $('.remove-item').click(function(e) {
        let itemId = $(this).attr('class').split('remove_')[1];
        
        let url = `/cart/remove/${itemId}/`;
        let csrfToken = "{{ csrf_token }}";
        let data = {'csrfmiddlewaretoken': csrfToken};

        $.post(url, data)
         .done(function() {
             location.reload();
         });
    })
</script>
{% endblock %}