blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.blog_details, name='blog_details'),
    path('<int:blog_id>/add/', views.add_comment, name='add_comment'),
    path('update/<int:comment_id>/',
         views.update_comment, name='update_comment'),
    path('delete/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),
]

virtual_yoga_room/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('items/', include('items.urls')),
    path('questions/', include('questions.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('profiles/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=300, null=False, blank=False)
    content = models.TextField(blank=False)
    date = models.DateField(null=True, blank=True)
    author = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='comments')
    comment = models.CharField(max_length=300, null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    user = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.comment

blog/forms.py
from django.forms import ModelForm
from . models import Comment
from django.contrib.auth.models import User


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

blog/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Blog, Comment
from .forms import CommentForm


def all_blogs(request):
    """ A view to render all blogs into blogs template """
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/blog.html', {'blogs': blogs})


def blog_details(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    comments = blog.comments.filter(active=True).order_by("-date")
    comment_form = CommentForm()

    return render(request, 'blog/blog-details.html', {
        'blog': blog,
        'comments': comments,
        'comment_form': comment_form,
    })


@login_required
def add_comment(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    new_comment = None
    comment_form = CommentForm()

    # comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            try:
                # Create Comment object but does not save to db
                new_comment = comment_form.save(commit=False)
                # checks user is the one making the comments
                new_comment.user = request.user
                # assign the current blog to the comment
                new_comment.blog = blog
                # save the comment to the db
                new_comment.save()
                return redirect(reverse('blog:blog_details', args=[blog.id]))
            except ValueError:
                messages.error(
                    request, 'Invalid information. Please try again.')
        else:
            comment_form = CommentForm()

    context = {
        'blog': blog,
        'comment_form': comment_form,
        'new_comment': new_comment
    }
    template = ('blog/blog-details.html')
    return render(request, template, context)


@login_required
def update_comment(request, comment_id, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    comment = get_object_or_404(Comment, pk=comment_id, user=request.user)

    if request.method == 'GET':
        comment_form = CommentForm(instance=comment)
        return render(request, 'blog/comment-update.html',
                      {'comment_form': comment_form})
    else:
        try:
            comment_form = CommentForm(
                request.POST, instance=comment)
            comment_form.save()
            return redirect(reverse('blog:blog_details', args=[blog.id]))
        except ValueError:
            messages.error(
                request, 'Invalid information. Please try again.')
            return render(request, 'blog/comment-update.html',
                          {
                            'comment': comment,
                            'comment_form': comment_form,
                          })


@login_required
def delete_comment(request, comment_id, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    comment = get_object_or_404(Comment, pk=comment_id, user=request.user)
    if request.method == 'POST':
        comment.delete()
        messages.success(request, 'Comment deleted!')
        return redirect(reverse('blog:blog_details', args=[blog.id]))

blog/templates/blog/blog-details.html
{% extends "base.html" %}
{% load static %}
{% block extra_title %}Blog Details{% endblock %}

{% block content %}
<header>
    {% include 'includes/main-nav.html' %}
</header>

<section class="margin-top-navbar">
    <!--Main content-->
    <div class="container-fluid">
        
        <!--breadcrumbs row with active page-->
        <div class="row">
            <div class="col">
                {% include 'blog/includes/breadcrumbs.html' %}
            </div>
        </div>

        <!--title row-->
        <div class="row">
            <div class="col text-center my-3">
                <h2 class="heading-font heading-item pb-2">{{ blog.title }}</h2>
            </div>
        </div>

        <!--page content row - content is formated with html when imputted in django admin-->
        <div class="row pb-3">
            <div class="col-10 offset-1 mb-3">
            
                <p class="mb-0 text-muted text-center"><small>{{ blog.date|date:'jS M Y'}}</small></p>
                <p class="text-muted text-center"><small>{{ blog.author }}</small></p>
                <p class="text-med">{{ blog.content|safe }}</p>
            </div>
        </div>
        <div class="row pb-3">
            <div class="col-10 offset-1 mb-5">
                <p><em>{{ comments.count }} comment{{comments.count|pluralize}} </em><i class="fas fa-meteor pink ms-2"></i></p>
                <hr>
                <!--display of all comments related to the post-->
                {% for post in comments %}
                
                    {% autoescape on %}
                        <p class="logo-green"><i class="fas fa-sticky-note logo-green me-2"></i>{{ post.comment }}</p>
                        <p class="text-muted">{{ post.user.username }}</p>
                    {% endautoescape %}
                
                    <p class="text-muted"><small>{{ post.date|date:'d M Y'}}</small></p>
                    <a href="{% url 'blog:update_comment' post.id %}" class="text-decoration-none dark-pink text-end"><i class="fas fa-pencil-alt"></i></a>
                    <a href="{% url 'blog:delete_comment' post.id %}" class="text-decoration-none dark-pink text-end"><i class="fas fa-times"></i></a>
                    
                        <hr>
                {% endfor %}
            </div>

           <div class="col-10 offset-1 mb-5">
                <div class="card-body">

                    {% if new_comment %}
                        <div class="alert alert-success" role="alert">
                            Your comment is waiting moderation
                        </div>
                    {% else %}
                        <p class="text-decoration-none logo-green"><i class="far fa-edit me-1"></i> Leave a comment</p>
                        <div>
                            <form method="POST" action="{% url 'blog:add_comment' blog.id %}">
                                {{ comment_form|crispy }}
                                {% csrf_token %}
                                    <button type="submit" class="btn white bg-dark-pink shadow">Submit</button>
                            </form>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        
    </div>
</section>
{% endblock %}

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}
{% block extra_title %}Blog{% endblock %}

{% block content %}
<header>
    {% include 'includes/main-nav.html' %}
</header>

<section class="margin-top-navbar">
    <!--Main content-->
    <div class="container-fluid">

        <!--breadcrumbs row with active page-->
        <div class="row">
            <div class="col">
                {% include 'blog/includes/breadcrumbs.html' %}
            </div>
        </div>

        <!--title row-->
        <div class="row">
            <div class="col text-center my-3">
                <h2 class="heading-font heading-item pb-2">Virtual Yoga Blog</h2>
            </div>
        </div>

        <!--blog content summary presented in a loop -  only 300 character displayed of content, button to
             read more opens to full blog conten on individual page-->
        <div class="row">
            <div class="col-10 offset-1 mb-5">
                <p><em>{{ blogs.count }} blog{{ blogs.count|pluralize }} published  </em><i class="fas fa-meteor pink"></i></p>
            </div>
        </div>
        <div class="row pb-3">
            {% for blog in blogs %}
            <div class="col-10 offset-1 mb-5">

                <h3><a href="{% url 'blog:blog_details' blog.id %}" class="text-decoration-none logo-green"><i
                            class="far fa-newspaper me-1"></i> {{ blog.title }}</a></h3>
                <p class="mb-0 text-muted">{{ blog.date|date:'d M Y'}}</p>
                <p class="text-muted">{{ blog.author }}</p>
                <p class="">{{ blog.content|safe|truncatechars:300 }}</p>
                <a class="btn btn-outline-secondary btn-sm shadow-sm"
                    href="{% url 'blog:blog_details' blog.id %}"><strong>read more</strong></a>

            </div>
            {% endfor %}
        </div>

    </div>
</section>
{% endblock %}

blog/templates/blog/comment-update.html
{% extends "base.html" %}
{% load static %}
{% block extra_title %}Blog Details{% endblock %}

{% block content %}
<header>
    {% include 'includes/main-nav.html' %}
</header>

<section class="margin-top-navbar">
    <!--Main content-->
    <div class="container-fluid">
        
        <!--breadcrumbs row with active page-->
        <div class="row">
            <div class="col">
                {% include 'blog/includes/breadcrumbs.html' %}
            </div>
        </div>

        <!--title row-->
        <div class="row">
            <div class="col text-center my-3">
                <h2 class="heading-font heading-item pb-2">{{ blog.title }}</h2>
            </div>
        </div>

        <!--page content row - content is formated with html when imputted in django admin-->
        <div class="row pb-3">
            <div class="col-10 offset-1 mb-3">
                    <form method="POST" >
                        {{ comment_form|crispy }}
                        {% csrf_token %}
                        <a href="{% url 'blog:blog_details' comment_form.blog.id %}" class="btn btn-outline-dark">cancel</a>
                            <button type="submit" class="btn white bg-dark-pink shadow">Save</button>
                    </form>
            </div>
        </div>
        
    </div>
</section>
{% endblock %}