blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.blog_details, name='blog_details'),
    path('<int:blog_id>/add/', views.add_comment, name='add_comment'),
    path('update/<int:comment_id>/',
         views.update_comment, name='update_comment'),
    path('delete/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home')
]

items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('lectures/', views.all_lectures, name='lectures'),
    path('programs/', views.all_programs, name='programs'),
    path('lectures/<int:lecture_id>',
         views.lecture_details, name='lecture_details'),
    path('programs/<int:program_id>',
         views.program_details, name='program_details'),
]

virtual_yoga_room/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('items/', include('items.urls')),
    path('questions/', include('questions.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('profiles/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=254, null=True)

    def __str__(self):
        return self.name


class Program(models.Model):
    class Meta:
        ordering = ['-id']

    CATEGORY = (
        ('Easy', 'Easy'),
        ('Moderate', 'Moderate'),
        ('Hard', 'Hard')
    )

    sku = models.CharField(max_length=254)
    name = models.CharField(max_length=254)
    category = models.CharField(max_length=254, null=True, choices=CATEGORY)
    description = models.TextField()
    number_lectures = models.IntegerField()
    image_url = models.URLField(max_length=1024, blank=True)
    image = models.ImageField()
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    rating = models.DecimalField(
        max_digits=6, decimal_places=1, null=True, blank=True)
    instructor = models.CharField(max_length=254)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name


class Lecture(models.Model):
    class Meta:
        ordering = ['-id']

    sku = models.CharField(max_length=254)
    name = models.CharField(max_length=254)
    program = models.ForeignKey(
        'Program', null=True,  on_delete=models.SET_NULL)
    description = models.TextField()
    video = models.URLField(max_length=1024, blank=True)
    image_url = models.URLField(max_length=1024, blank=True)
    image = models.ImageField()
    rating = models.DecimalField(
        max_digits=6, decimal_places=1, null=True, blank=True)
    instructor = models.CharField(max_length=254)

    def __str__(self):
        return self.name

items/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.db.models import Q
from django.db.models.functions import Lower
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Lecture, Program


def all_programs(request):
    """ A view to show all programs, including sorting and search queries """
    programs = Program.objects.all()
    program_count = programs.count()

    query = None
    sort = None
    direction = None

    if request.GET:

        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                programs = programs.annotate(lower_name=Lower('name'))
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            programs = programs.order_by(sortkey)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('items:programs'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            programs = programs.filter(queries)
            program_count = programs.count()

    current_sorting = f'{sort}_{direction}'

    page = request.GET.get('page', 1)

    paginator = Paginator(programs, 4)

    try:
        programs = paginator.page(page)
    except PageNotAnInteger:
        programs = paginator.page(1)
    except EmptyPage:
        programs = paginator.page(paginator.num_pages)

    context = {
        'programs': programs,
        'program_count': program_count,
        'page': page,
        'search_term': query,
        'current_sorting': current_sorting
    }

    return render(request, 'items/programs.html', context)


def all_lectures(request):
    """ A view to show all lectures, including sorting and search queries """

    lectures = Lecture.objects.all()
    lectures_count = lectures.count()

    query = None
    sort = None
    direction = None

    if request.GET:

        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                lectures = lectures.annotate(lower_name=Lower('name'))
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            lectures = lectures.order_by(sortkey)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('items:lectures'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            lectures = lectures.filter(queries)
            lectures_count = lectures.count()

    current_sorting = f'{sort}_{direction}'

    page = request.GET.get('page', 1)
    paginator = Paginator(lectures, 6)
    try:
        lectures = paginator.page(page)
    except PageNotAnInteger:
        lectures = paginator.page(1)
    except EmptyPage:
        lectures = paginator.page(paginator.num_pages)

    context = {
        'lectures': lectures,
        'lectures_count': lectures_count,
        'search_term': query,
        'current_sorting': current_sorting,
        'page': page
    }

    return render(request, 'items/lectures.html', context)


def program_details(request, program_id):
    """ A view to show individual program details """

    program = get_object_or_404(Program, pk=program_id)
    selected_lectures = program.lecture_set.all()

    # paginator code
    paginator = Paginator(selected_lectures, 2)
    pageMd = request.GET.get('page')
    pageLg = request.GET.get('page')
    selected_lectures_md = paginator.get_page(pageMd)
    paginatorLg = Paginator(selected_lectures, 3)
    selected_lectures_lg = paginatorLg.get_page(pageLg)

    context = {
        'program': program,
        'selected_lectures': selected_lectures,
        'selected_lectures_md': selected_lectures_md,
        'selected_lectures_lg': selected_lectures_lg,
    }

    return render(request, 'items/program-details.html', context)


def lecture_details(request, lecture_id):
    """ A view to show individual lecture details """
    item = get_object_or_404(Lecture, pk=lecture_id)
    context = {
        'item': item,
    }

    return render(request, 'items/lecture-details.html', context)

items/templates/items/includes/breadcrumbs.html
<div class="row mt-3">
    <div class="col-12">
        <!-- Breadcrumbs to facilitate navigation - with links to previous pages -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home:home' %}"
                        class="breadcrumbs-text logo-green pl-2"> Home</a></li>

                <!-- second crumb - programs - provides a link to guide the user to the programs page-->
                <li class="breadcrumb-item">
                    <a href="{% url 'items:programs' %}" class="breadcrumbs-text logo-green pl-2">All Programs</a>
                </li>

                <!-- third crumb - lectures - provides a link to guide the user to all lectures page-->
                <li class="breadcrumb-item">
                    <a href="{% url 'items:lectures' %}" class="breadcrumbs-text logo-green pl-2">All lectures</a>
                </li>
            </ol>
        </nav>
    </div>
</div>

items/templates/items/includes/lecture-content.html
<!-- Details of the lecture content -->
        <div class="row mx-1 mb-5" id="programDetailRow">
            <div class="col-md-5">
                <img class="img-fluid shadow-sm" src="{{ item.image.url }}" alt="{{ item.name }}">
            </div>
            <div class="col-md-7">
                <h6 class="card-subtitle pb-3"><small>Program:</small>
                    <a href="" class="text-decoration-none logo-green ml-1"> {{ item.program }}</a>
                </h6>
                <h5
                    class="card-title bg-logo-green d-flex align-items-center justify-content-center text-center white px-1 py-2">
                    {{ item.name }}</h5>
                <p class="text-md ps-2">{{ item.description|safe }}</p>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item text-center text-muted">{{ item.instructor }}</li>
                    <li class="list-group-item text-center">
                        <small class="text-muted logo-green"><i class="fas fa-star logo-green pr-2"></i>
                            {{ item.rating }} / 5</small>
                    </li>
                </ul>
                <div class="card-body row my-2">
                    <div class="d-flex justify-content-center col-12 col-md-6">
                        <form class="form" action="{% url 'cart:add_to_cart' item.program.id %}" method="POST">
                            {% csrf_token %}
                            <input name="quantity" type="hidden" value="1">
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            <input type="submit" class="btn bg-pink text-center shadow px-3" value="Buy Program">
                        </form>
                    </div>
                    <div class="d-flex justify-content-center col-12 col-md-6">
                        <a href="{% url 'items:program_details' item.program.id %}" class="btn btn-outline-dark text-center "><small>Program Details</small></a>
                    </div>
                </div>
            </div>
        </div>

items/templates/items/includes/lectures-loop.html
<div class="row pb-3">

    <!-- loop iterating through 6 lectures in each page -->
    {% for lecture in lectures %}
    <div data-aos="fade-up" class="col-md-6 col-lg-4">
        <div class="card lectures-card shadow-lg mb-5 mx-3">
            <a href="{% url 'items:lecture_details' lecture.id %}">
                <img class="card-img-top img-fluid shadow" src="{{ lecture.image.url }}" alt="{{ lecture.name }}">
            </a>
            <div class="card-body">

                <h6 class="card-subtitle pb-2"><small>Program:</small>
                    <a href="" class="text-decoration-none logo-green ml-1"> {{ lecture.program }}</a>
                </h6>
                <h5
                    class="card-title bg-logo-green d-flex align-items-center justify-content-center text-center white px-1 py-2">
                    {{ lecture.name }}</h5>
                <p class="card-text text-md">{{ lecture.description|safe|truncatewords:20 }}</p>
                <a class="text-decoration-none dark-pink text-shadow ms-1" href="{% url 'items:lecture_details' lecture.id %}">
                    <strong>read more</strong>
                </a>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item dark-pink"><i class="fas fa-thermometer-half me-2 "></i> {{ lecture.program.category }}</li>
                <li class="list-group-item text-muted">{{ lecture.instructor }}</li>
                <li class="list-group-item">
                    <small class="text-muted logo-green"><i class="fas fa-star logo-green pr-2"></i> {{ lecture.rating }} / 5</small>
                </li>
            </ul>
            <div class="card-body row my-2">
                <div class="d-flex justify-content-center col-12 col-md-6">
                    <form class="form" action="{% url 'cart:add_to_cart' lecture.program.id %}" method="POST">
                        {% csrf_token %}
                        <input name="quantity" type="hidden" value="1">
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        <input type="submit" class="btn bg-pink text-center shadow px-3" value="Buy Program">
                    </form>
                </div>
                <div class="d-flex justify-content-center col-12 col-md-6">
                    <a href="{% url 'items:lecture_details' lecture.id %}" class="btn btn-outline-dark text-center "><small>More Details</small></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

items/templates/items/includes/lectures-pagination.html
<!-- Pagination added based on bootstrap and django documentation -->
    <nav aria-label="Page navigation example">
        {% if lectures.has_other_pages %}
        <ul class="pagination d-flex justify-content-center">
            {% if lectures.has_previous %}
            <li class="page-item"><a class="page-link logo-green"
                    href="?page={{ lectures.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true"><span>&laquo;</span></a>
            </li>
            {% endif %}

            {% for i in lectures.paginator.page_range %}
            {% if lectures.number == i %}
            <li class="page-item active" aria-current="page">
                <span class="page-link bg-logo-green active-borders white">{{ i }} <span
                        class="sr-only">(current)</span></span>
            </li>
            {% elif i > lectures.number|add:'-3' and i < lectures.number|add:'3' %}

            <li class="page-item">
                <a class="page-link logo-green" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if lectures.has_next %}
            <li class="page-item">
                <a class="page-link logo-green" href="?page={{ lectures.next_page_number }}">&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true"><span>&raquo;</span></a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </nav>

items/templates/items/includes/program-content.html
{% load static %}

<div class="row mx-1 mb-5" id="programDetailRow">
    <div class="col-md-5">
        <a href="{% url 'items:program_details' program.id %}">
            <img class="img-fluid shadow-sm" src="{{ program.image.url }}" alt="{{ program.name }}">
        </a>
    </div>
    <div class="col-md-7">
        <h5 class="bg-logo-green d-flex align-items-center justify-content-center text-center white px-1 py-2">
            {{ program.name }}</h5>
        <p class="text-md px-1">{{ program.description|safe }}</p>
        <ul class="list-group list-group-flush">
            <li class="list-group-item text-center">{{ program.number_lectures }} lectures</li>
            <li class="list-group-item text-center text-muted">{{ program.instructor }}</li>
            <li class="list-group-item text-center">
                <small class="text-muted text-center logo-green"><i class="fas fa-star logo-green pr-2"></i>
                    {{ program.rating }} / 5</small>
            </li>
            <li class="list-group-item text-center mt-3">
                <!-- Post form to add program to the cart -->
                <form class="form" action="{% url 'cart:add_to_cart' program.id %}" method="POST">
                    {% csrf_token %}
                    <input name="quantity" type="hidden" value="1">
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                    <input type="submit" class="btn bg-pink text-center shadow px-3" value="Add to Cart">
                </form>
            </li>
        </ul>
    </div>
</div>

<!-- Lectures included in the program -->
<!-- custom owl carousel of selected lectures with pagination logic not displaying cards for mobile view -->
<div class="container-fluid bg-offwhite p-0 m-0" id="selectedLectures">
    <div class="row mt-3 py-3">
        <div class="col-12">
            <p class="text-center"><i class="fas fa-spa pink me-2"> | </i><strong>{{ program.number_lectures }} Lectures Included</strong></p>
            <h5 class="text-center d-none d-md-block pb-2">Program: {{ program.name }} </h5>
        </div>
    </div>

    <!-- costum carousel of with pagination logic  not displaying cards for mobile view -->
    <div class="row d-none d-md-flex d-lg-none pb-2">

        {% for lecture in selected_lectures_md %}
        <div data-aos="fade-right" data-aos-duration="1100" class="col-md-6">
            {% include 'items/includes/selected-lectures.html' %}
        </div>
        {% endfor %}
    </div>
    <div class="row d-none d-lg-flex pb-2">

        {% for lecture in selected_lectures_lg %}
        <div data-aos="fade-right" data-aos-duration="1100" class="col-lg-4">
            {% include 'items/includes/selected-lectures.html' %}
        </div>
        {% endfor %}
    </div>

    <!-- costum carousel of with pagination logic  not displaying cards for mobile view -->

    <!-- previous and next arrows layout for medium size screens -->
    <div class="row d-none d-md-flex d-lg-none pb-5">
        <div class="col-md-6 offset-3">
            <ul class="pagination d-flex justify-content-center">

                {% if selected_lectures_md.has_previous %}
                <li class="page-item">
                    <a class="text-decoration-none d-flex align-items-center dark-pink shadow px-2 py-1 me-5"
                        href="?page={{ selected_lectures_md.previous_page_number }} #selectedLectures"><i
                            class="fas fa-angle-left fa-lg"></i></a>
                </li>
                {% else %}
                <li class="page-item">
                    <p class="text-decoration-none text-muted me-5">
                        <i class="fas fa-angle-left fa-lg"></i>
                    </p>
                </li>
                {% endif %}

                <li class="page-item">
                    <p class="text-decoration-none text-muted me-5"><i class="far fa-circle"></i></p>
                </li>

                {% if selected_lectures_md.has_next %}
                <li class="page-item">
                    <a class="dark-pink shadow px-2 py-1 d-flex align-items-center text-decoration-none"
                        href="?page={{ selected_lectures_md.next_page_number }} #selectedLectures"><i
                            class="fas fa-angle-right fa-lg"></i></a>
                </li>
                {% else %}
                <li class="page-item">
                    <p class="text-decoration-none text-muted me-5">
                        <i class="fas fa-angle-right fa-lg"></i>
                    </p>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>

    <!--layout of previous and next buttons for large screens and bigger -->
    <div class="row d-none d-lg-flex pb-5">
        <div class="col-md-4 offset-4">
            <ul class="pagination d-flex justify-content-center">

                {% if selected_lectures_lg.has_previous %}
                <li class="page-item">
                    <a class="text-decoration-none dark-pink d-flex align-items-center shadow px-2 py-1 me-5"
                        href="?page={{ selected_lectures_lg.previous_page_number }} #selectedLectures"><i
                            class="fas fa-angle-left fa-lg"></i></a>
                </li>
                {% else %}
                <li class="page-item">
                    <p class="text-decoration-none text-muted me-5">
                        <i class="fas fa-angle-left fa-lg"></i>
                    </p>
                </li>
                {% endif %}

                <li class="page-item">
                    <p class="text-decoration-none text-muted me-5"><i class="far fa-circle"></i></p>
                </li>

                {% if selected_lectures_lg.has_next %}
                <li class="page-item">
                    <a class="dark-pink shadow px-2 py-1 d-flex align-items-center text-decoration-none"
                        href="?page={{ selected_lectures_lg.next_page_number }} #selectedLectures"><i
                            class="fas fa-angle-right fa-lg"></i></a>
                </li>
                {% else %}
                <li class="page-item">
                    <p class="text-decoration-none text-muted me-5">
                        <i class="fas fa-angle-right fa-lg"></i>
                    </p>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>
</div>

items/templates/items/includes/programs-loop.html
<div class="row pb-3">
    {% if not programs %}
        <div class="col-12 text-center mt-2 mb-4" >
            <h5>Sorry, no programs were found matching your search query.</h5>
        </div>
    {% else %}
    <!-- loop iterating through 4 programs in each page -->
        {% for program in programs %}
        <div data-aos="fade-up" class="col-12 justify-content-center">
            <div class="card lectures-card shadow-lg mb-5 mx-3 g-0">
                <div class="row mx-1">
                    <div class="col-md-5 mt-3">
                        <a href="{% url 'items:program_details' program.id %}">
                            <img class="card-img-top img-fluid shadow" src="{{ program.image.url }}"
                                alt="{{ program.name }}">
                        </a>
                    </div>
                    <div class="col-md-7">
                        <div class="card-body px-0">
                            <h5
                                class="card-title bg-logo-green d-flex align-items-center justify-content-center text-center white px-1 py-2">
                                {{ program.name }}</h5>
                            <p class="card-text text-md d-none d-md-flex">{{ program.description|safe|truncatewords:200 }}</p>
                            <a class="text-decoration-none dark-pink text-shadow text-md d-none d-md-flex ms-1" href="{% url 'items:program_details' program.id %}">
                                <strong>read more</strong>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row pt-2">
                    <div class="col">
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item text-center dark-pink"><i class="fas fa-thermometer-half me-3"></i> {{ program.category }}</li>
                                <li class="list-group-item text-center">{{ program.number_lectures }} lectures</li>
                                <li class="list-group-item text-center text-muted">{{ program.instructor }}</li>
                                <li class="list-group-item text-center">
                                    <small class="text-muted logo-green"><i class="fas fa-star logo-green pr-2"></i>
                                        {{ program.rating }} / 5</small>
                                </li>
                                <li class="list-group-item text-muted">£{{ program.price }}</li>
                            </ul>
                            <div class="card-body d-flex justify-content-evenly my-2">
                                 <form class="form" action="{% url 'cart:add_to_cart' program.id %}" method="POST">
                                    {% csrf_token %}
                                    <input name="quantity" type="hidden" value="1">
                                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                    <input type="submit" class="btn bg-pink text-center shadow px-3" value="Add to Cart">
                                </form>
                                <a href="{% url 'items:program_details' program.id %}" class="btn btn-outline-dark text-center d-none d-md-flex"><small>More Details</small></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endif%}
</div>

items/templates/items/includes/programs-pagination.html
 <!-- Pagination added based on bootstrap and django documentation -->
        <nav aria-label="Page navigation example">
            {% if programs.has_other_pages %}
            <ul class="pagination d-flex justify-content-center">
                {% if programs.has_previous %}
                <li class="page-item"><a class="page-link logo-green"
                        href="?page={{ programs.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true"><span>&laquo;</span></a>
                </li>
                {% endif %}
                {% for i in programs.paginator.page_range %}
                {% if programs.number == i %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link bg-logo-green active-borders" href="#"><span class="white">{{ i }} <span
                                class="sr-only">(current)</span></span></a>
                </li>
                {% else %}

                <li class="page-item">
                    <a class="page-link logo-green" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endif %}
                {% endfor %}
                {% if programs.has_next %}
                <li class="page-item">
                    <a class="page-link logo-green" href="?page={{ programs.next_page_number }}">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true"><span>&raquo;</span></a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </nav>

items/templates/items/includes/selected-lectures.html
<div class="card shadow-lg mb-5 mx-4">
    <div class="card-body text-center">
        <h5 class="card-title pb-2">{{ lecture.name }}</h5>
        <ul class="list-group list-group-flush text-center">
            <li class="list-group-item text-muted"></li>
            <li class="list-group-item"><small class="text-muted logo-green"><i class="fas fa-star logo-green pr-2"></i>
                    {{ lecture.rating }} / 5</small>
            </li>
        </ul>
        <div class="card-body d-flex justify-content-center my-2">
            <a href="{% url 'items:lecture_details' lecture.id %}"
                class="btn bg-logo-green white small-btn text-center">More
                Info</a>
        </div>
    </div>
</div>

items/templates/items/includes/sorting-box.html
<div class="sort-select-wrapper w-50">
    <select id="sort-selector"
        class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}dark{% endif %}">
        <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...
        </option>
        {% if programs %}
            <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low
                to high)</option>
            <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price
                (high to low)</option>
        {% endif %}
        <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating
            (low to high)</option>
        <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating
            (high to low)</option>
        <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)
        </option>
        <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)
        </option>
    </select>
</div>